message("MRS_INCLUDE_DIR: ${MRS_INCLUDE_DIR}")
message("MRS_LIBRARY_DIR: ${MRS_LIBRARY_DIR}")

message("MRS_PLATFORM_TYPE=${MRS_PLATFORM_TYPE}")

set(CMAKE_MACOSX_RPATH 1)

include_directories(${MRS_INCLUDE_DIR})

set(MRS_STATIC_LINK_LIBRARIES)
set(MRS_SHARED_LINK_LIBRARIES)
if(MRS_PLATFORM_TYPE MATCHES "windows")
    include(${CMAKE_CURRENT_LIST_DIR}/windows.cmake)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHsc")
    set(LIBMRS ${MRS_LIBRARY_DIR}/mrs.lib  ${MRS_LIBRARY_DIR}/enet.lib ${MRS_LIBRARY_DIR}/uv.lib ${MRS_LIBRARY_DIR}/ssl.lib ${MRS_LIBRARY_DIR}/crypto.lib)
    if(EXISTS ${MRS_LIBRARY_DIR}/decrepit.lib)
        set(LIBMRS ${LIBMRS} ${MRS_LIBRARY_DIR}/decrepit.lib)
    endif()
    set(MRS_STATIC_LINK_LIBRARIES Ws2_32.lib psapi.lib Iphlpapi.lib Userenv.lib winmm.lib Advapi32.lib Gdi32.lib Crypt32.lib)
else()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -Wall")
    set(LIBMRS ${MRS_LIBRARY_DIR}/libmrs.a ${MRS_LIBRARY_DIR}/libenet.a ${MRS_LIBRARY_DIR}/libuv.a ${MRS_LIBRARY_DIR}/libssl.a ${MRS_LIBRARY_DIR}/libcrypto.a)
    if(EXISTS ${MRS_LIBRARY_DIR}/libdecrepit.a)
        set(LIBMRS ${LIBMRS} ${MRS_LIBRARY_DIR}/libdecrepit.a)
    endif()
    
    if(CMAKE_SYSTEM_NAME MATCHES "Darwin")
        if(NOT EXISTS ${MRS_LIBRARY_DIR}/libdecrepit.a)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fembed-bitcode")
        endif()
    else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
    endif()
    
    if(MRS_PLATFORM_TYPE MATCHES "mac")
        add_definitions("-DMRS_MAC")
    elseif(MRS_PLATFORM_TYPE MATCHES "ios")
        add_definitions("-DMRS_IOS")
    elseif(MRS_PLATFORM_TYPE MATCHES "tvos")
        add_definitions("-DMRS_TVOS")
    elseif(MRS_PLATFORM_TYPE MATCHES "linux")
        add_definitions("-DMRS_LINUX")
        set(MRS_SHARED_LINK_LIBRARIES pthread rt dl)
    endif()
endif()
set(MRS_STATIC_LINK_LIBRARIES ${MRS_STATIC_LINK_LIBRARIES} ${LIBMRS})
set(MRS_LINK_LIBRARIES ${MRS_STATIC_LINK_LIBRARIES} ${MRS_SHARED_LINK_LIBRARIES})
message("MRS_LINK_LIBRARIES: ${MRS_LINK_LIBRARIES}")
